#!/usr/bin/python3
import math
import sys
import numpy

def vector_vertical():
    if len(sys.argv) != 6:
        exit (84)

    vector = numpy.zeros((1, 3))
    print(vector)
    x = float(sys.argv[1])
    y = float(sys.argv[2])
    print(x)
    print(y)

def translation():
    i = float(sys.argv[4])
    j = float(sys.argv[5])
    print("1.00\t0.00\t" + "%.2f" % i)
    print("0.00\t1.00\t" + "%.2f" % j)
    print("0.00\t0.00\t1.00")

translation()
