##
## EPITECH PROJECT, 2022
## make doop
## File description:
## make doop
##

NAME	= do-op

SRC	= do_op.c

OBJ	= $(SRC:.c=.o)

all: $(NAME)

$(NAME):
	gcc $(SRC) -o $(NAME) -L ../lib/my/ -lmy

clean:
	rm -f $(OBJ)
